export const variables = {
  loginLabel: 'Login',
  emailLabel: 'Email',
  passwordLabel: 'Password *',
  passwordMismatchError: "Passwords don't match",
  signInLabel: "Don't have an account? Sign up!",
  nameLabel: 'First Name',
  lastNameLabel: 'Last Name', 
  birthdayLabel: 'Birthday',
  confirmPasswordLabel: 'Confirm Password *',
  registrationLabel: 'Create your own profile',
  confirmLabel: 'Confirm', 
  logoShorthand: '.B',
  booksLabel: 'Books', 
  reviewsLabel: 'Reviews',
  settingsLabel: 'Settings',
  submitLabel: 'Submit',
  fileNotSupported: 'File not supported',
  newBooksLabel: 'Add new book',
  titleLabel: 'Title',
  authorFirstNameLabel: 'Author Name',
  authorLastNameLabel: 'Author Last Name',
  descriptionLabel: 'Description',
  isbnLabel: 'ISBN',
  pagesLabel: 'Pages',
  newReviewLabel: 'Add a new review',
  chooseBookLabel: 'Choose a book',
  startDateLabel: 'Start date',
  finishDateLabel: 'Finish date',
  ratingLabel: 'Rating',
  reviewLabel: 'Give your opinion!'
  
}